### ISSUE TITLE
Кнопка виджетов

### ISSUE THREAD

**Issue by k-egor-smirnov** [mmarkelov/react-vk#1]
Будет реализована поддержка кнопок для установки виджета?
https://vk.com/dev/apps_widgets

**Comment by mmarkelov** [comment]
@k-egor-smirnov привет! Спасибо за предложение. Изначально такой функционал не рассматривался, но надо признать - идея хорошая. Понадобится переписать код, возможно придется делать отдельный модуль, соответственно на это уйдет некоторое время. В ближайшее время постараюсь приступить к реализации. Спасибо еще раз!
