### ISSUE TITLE
AllowMessagesFromCommunity: Cannot read property 'Widgets' of undefined

### ISSUE THREAD

**Issue by undermuz** [mmarkelov/react-vk#12]
Code:
![image](https://user-images.githubusercontent.com/6875507/52413275-361f8b80-2af2-11e9-8f15-86a4e9b24af0.png)

Trace:
![image](https://user-images.githubusercontent.com/6875507/52413223-feb0df00-2af1-11e9-97d7-f9d0ff0067c4.png)

Error line:
https://github.com/mmarkelov/react-vk/blob/master/src/AllowMessagesFromCommunity.js#L39
![image](https://user-images.githubusercontent.com/6875507/52413249-16886300-2af2-11e9-889a-17f1a9b5749d.png)

Packages:
![image](https://user-images.githubusercontent.com/6875507/52413298-49325b80-2af2-11e9-8610-29b1532230cb.png)

**Comment by mmarkelov** [comment]
@undermuz latest **react-vk** need **react** >= **16.6**. So there are two ways:

1. Install **react-vk** version **3.5.2**

2. Update **react**

You can check example with **react 16.4.2** [here](https://codesandbox.io/s/71lw01yp76)

**Comment by undermuz** [comment]
@mmarkelov thank you for answer

Please, update readme:
https://github.com/mmarkelov/react-vk#install

> react-vk@1.1.5 for react < 16 react-vk@1.1.6 for react > 16.2 react-vk for react > 16.3
