### ISSUE TITLE
getUserInfo

### ISSUE THREAD

**Issue by KovalevAnton** [mmarkelov/react-vk#17]
Hallo! How can i get user info with react-vk? Is there an api for this?

**Comment by mmarkelov** [comment]
@KovalevAnton I suppose that the simplest way is to use [Auth](https://mmarkelov.github.io/react-vk/#/login) component with **onAuth** callback:
```javascript
<VK apiId={your_api_id}>
	      <Auth options={{
	              onAuth: user => {
                       // user info is here
	                console.log(user);
	              },
            }}/>
```
Also you can check [this](https://vk.com/dev/openapi_2?f=4.%2B%D0%92%D1%8B%D0%B7%D0%BE%D0%B2%2B%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2%2BAPI%2B%D0%92%D0%9A%D0%BE%D0%BD%D1%82%D0%B0%D0%BA%D1%82%D0%B5)
