### ISSUE TITLE
call vk.Widgets.Like(elementId, options, pageId) with 2 arguments if page_id was't specified

### ISSUE THREAD

**Issue by kitos** [mmarkelov/react-vk#3]
According to documentation page_id is optional parameter in "Like" widget.

**Comment by mmarkelov** [comment]
@kitos fixed in 'master' branch. Thanks!

**Comment by kitos** [comment]
Thank you for quick fix. Looks like it works, but this time I faced another problem - button is not updated during client navigation though different pages

here is app using your package and issue: https://github.com/kitos/web-purple/issues/240

**Comment by kitos** [comment]
I guess we can close this issue, and I'll try to investigate the reason of new one

**Comment by mmarkelov** [comment]
@kitos Thank you! And I try to find out what is wrong with updating during navigation ASAP
