### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by NarekChang** [mmarkelov/react-vk#4]
I get this 

> TypeError: (0 , _react.createContext) is not a function

My code:
`import React from 'react';`
`import { connect } from 'react-redux';`
`import { bindActionCreators } from 'redux';`
 
`import _ from 'lodash';`
`import { NavLink } from 'react-router-dom';`
 
`import { VK } from 'react-vk';`
 
`class Final extends React.Component{`
  `render(){`
    `return (`
     `<VK apiId={myAppId}><Like /></VK>`
    `);`
  `}`
`}`
 
`export default connect(`
  `state => ({ questData:state.currentQuest, userData:state.user }),`
  `dispatch => bindActionCreators({ loadQuest, startSession, getSceneType, PopupOpen }, ``dispatch),`
`)(Final);`

**Comment by ghost** [comment]
Can you name your react project version? I think that if it is < 16.3 you can try install react-vk@1.1.6 if you are using react@16.0 or if your react version is 15 you can install react-vk@1.1.5 and it should work fine. And thank you for issue. I will figure out on this dependencies problem

**Comment by NarekChang** [comment]
@mapkeji I updated to 16.3. Now I get error 

> invariant.js:42 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

**Comment by ghost** [comment]
@NarekChang interesting... Could I see your code here?

**Comment by NarekChang** [comment]
@mapkeji  @mmarkelov 

```
import React from 'react';
import { connect } from 'react-redux';
import { bindActionCreators } from 'redux';
 
import { VK, Like } from 'react-vk';
 
class Final extends React.Component{
  render(){
    return (
      <div>
        <VK apiId={myAppID}>
            <Like />
        </VK>
      </div>
    );
  }
}
 
export default connect(
  state => ({ userData:state.user }),
  dispatch => bindActionCreators({ loadQuest }, dispatch),
)(Final);

```

https://pastebin.com/JBMietVx

**Comment by mmarkelov** [comment]
@NarekChang I suppose it my might be problem with your own code, cause I don't see any problems with package. You can check it here
https://codesandbox.io/s/l75rvq20ml

**Comment by NarekChang** [comment]
@mmarkelov Ok. Do u have ideas why exist the error?

**Comment by mmarkelov** [comment]
@NarekChang Unfortunately, no ideas. Cause I don't know the error line and whole code of your application

**Comment by MartinSeeler** [comment]
For any Googler coming here like me, this has happened right after an update of React to 16.3. The fix for me was pretty easy: `rm -rf node_modules && yarn install`
