### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by prodislav** [mmarkelov/react-vk#6]
Hi, thx for great app, can u add option for get user email ?

**Comment by mmarkelov** [comment]
Hello, @prodislav! Actually VK Api does not send user email if you are using **onAuth** callback in **VK.Widgets.Auth** (**Auth** component from library). Maybe there is a solution with using **VK.Auth.login**, but I just haven't got any experience with it. So I should try it myself. I'll try to find solution which we can use with library. So I need some time to check it out, I'll try to do this ASAP.
Thanks!

**Comment by mmarkelov** [comment]
@prodislav To get email you can use auth with url:
```javascript
import React from "react";

const openVkAuth = () => {
  const url =
    "https://oauth.vk.com/authorize?client_id=CLIENT_ID&scope=email&response_type=token&redirect_uri=REDIRECT_URL";

  const newWin = window.open(url, "vk-login", "width=665,height=370");
  newWin.onload = function() {
    const { hash } = newWin.location;
    console.log(hash);
  };
};

const Login = () => <button onClick={openVkAuth}>Login with VK</button>;

export default Login;
```

You'll get email in get params on redirected page

You can checked more info [here](https://vk.com/dev/auth_sites)

**Comment by prodislav** [comment]
@mmarkelov Yeah, thank you so much. But for sure i dont know how to get email in case with your react component. cause now i've got 2 popup. its a problem

**Comment by mmarkelov** [comment]
@prodislav Actually you can not get user email with using **Auth** component, you just can use custom button, like [so](https://codesandbox.io/s/yjj0ro9y3v) and you'll get email in location hash.
Hope it'll help you
